// Generated by gencpp from file sas_robot_driver_franka/Grasp.msg
// DO NOT EDIT!


#ifndef SAS_ROBOT_DRIVER_FRANKA_MESSAGE_GRASP_H
#define SAS_ROBOT_DRIVER_FRANKA_MESSAGE_GRASP_H

#include <ros/service_traits.h>


#include <sas_robot_driver_franka/GraspRequest.h>
#include <sas_robot_driver_franka/GraspResponse.h>


namespace sas_robot_driver_franka
{

struct Grasp
{

typedef GraspRequest Request;
typedef GraspResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Grasp
} // namespace sas_robot_driver_franka


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::sas_robot_driver_franka::Grasp > {
  static const char* value()
  {
    return "6752ec080e002a60682f31654d420583";
  }

  static const char* value(const ::sas_robot_driver_franka::Grasp&) { return value(); }
};

template<>
struct DataType< ::sas_robot_driver_franka::Grasp > {
  static const char* value()
  {
    return "sas_robot_driver_franka/Grasp";
  }

  static const char* value(const ::sas_robot_driver_franka::Grasp&) { return value(); }
};


// service_traits::MD5Sum< ::sas_robot_driver_franka::GraspRequest> should match
// service_traits::MD5Sum< ::sas_robot_driver_franka::Grasp >
template<>
struct MD5Sum< ::sas_robot_driver_franka::GraspRequest>
{
  static const char* value()
  {
    return MD5Sum< ::sas_robot_driver_franka::Grasp >::value();
  }
  static const char* value(const ::sas_robot_driver_franka::GraspRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::sas_robot_driver_franka::GraspRequest> should match
// service_traits::DataType< ::sas_robot_driver_franka::Grasp >
template<>
struct DataType< ::sas_robot_driver_franka::GraspRequest>
{
  static const char* value()
  {
    return DataType< ::sas_robot_driver_franka::Grasp >::value();
  }
  static const char* value(const ::sas_robot_driver_franka::GraspRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::sas_robot_driver_franka::GraspResponse> should match
// service_traits::MD5Sum< ::sas_robot_driver_franka::Grasp >
template<>
struct MD5Sum< ::sas_robot_driver_franka::GraspResponse>
{
  static const char* value()
  {
    return MD5Sum< ::sas_robot_driver_franka::Grasp >::value();
  }
  static const char* value(const ::sas_robot_driver_franka::GraspResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::sas_robot_driver_franka::GraspResponse> should match
// service_traits::DataType< ::sas_robot_driver_franka::Grasp >
template<>
struct DataType< ::sas_robot_driver_franka::GraspResponse>
{
  static const char* value()
  {
    return DataType< ::sas_robot_driver_franka::Grasp >::value();
  }
  static const char* value(const ::sas_robot_driver_franka::GraspResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SAS_ROBOT_DRIVER_FRANKA_MESSAGE_GRASP_H
