// Generated by gencpp from file sas_robot_driver_franka/Move.msg
// DO NOT EDIT!


#ifndef SAS_ROBOT_DRIVER_FRANKA_MESSAGE_MOVE_H
#define SAS_ROBOT_DRIVER_FRANKA_MESSAGE_MOVE_H

#include <ros/service_traits.h>


#include <sas_robot_driver_franka/MoveRequest.h>
#include <sas_robot_driver_franka/MoveResponse.h>


namespace sas_robot_driver_franka
{

struct Move
{

typedef MoveRequest Request;
typedef MoveResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Move
} // namespace sas_robot_driver_franka


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::sas_robot_driver_franka::Move > {
  static const char* value()
  {
    return "73e650ba1526b28d9e3f1be7ee33a441";
  }

  static const char* value(const ::sas_robot_driver_franka::Move&) { return value(); }
};

template<>
struct DataType< ::sas_robot_driver_franka::Move > {
  static const char* value()
  {
    return "sas_robot_driver_franka/Move";
  }

  static const char* value(const ::sas_robot_driver_franka::Move&) { return value(); }
};


// service_traits::MD5Sum< ::sas_robot_driver_franka::MoveRequest> should match
// service_traits::MD5Sum< ::sas_robot_driver_franka::Move >
template<>
struct MD5Sum< ::sas_robot_driver_franka::MoveRequest>
{
  static const char* value()
  {
    return MD5Sum< ::sas_robot_driver_franka::Move >::value();
  }
  static const char* value(const ::sas_robot_driver_franka::MoveRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::sas_robot_driver_franka::MoveRequest> should match
// service_traits::DataType< ::sas_robot_driver_franka::Move >
template<>
struct DataType< ::sas_robot_driver_franka::MoveRequest>
{
  static const char* value()
  {
    return DataType< ::sas_robot_driver_franka::Move >::value();
  }
  static const char* value(const ::sas_robot_driver_franka::MoveRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::sas_robot_driver_franka::MoveResponse> should match
// service_traits::MD5Sum< ::sas_robot_driver_franka::Move >
template<>
struct MD5Sum< ::sas_robot_driver_franka::MoveResponse>
{
  static const char* value()
  {
    return MD5Sum< ::sas_robot_driver_franka::Move >::value();
  }
  static const char* value(const ::sas_robot_driver_franka::MoveResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::sas_robot_driver_franka::MoveResponse> should match
// service_traits::DataType< ::sas_robot_driver_franka::Move >
template<>
struct DataType< ::sas_robot_driver_franka::MoveResponse>
{
  static const char* value()
  {
    return DataType< ::sas_robot_driver_franka::Move >::value();
  }
  static const char* value(const ::sas_robot_driver_franka::MoveResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SAS_ROBOT_DRIVER_FRANKA_MESSAGE_MOVE_H
